Civix upgrade, replace deprecated debug command, copy legacycode class into extension to avoid dependency
systopia/de.systopia.fastactivity pull request #46
Opened 2023-10-05 13:32 UTC by jofranz

_internal reference: 21474_

2023-10-05 13:34 UTC, jofranz commented
@jensschuppe Please have a look. Sorry for the all-in-one branch approach. We should aim to avoid this.

2023-10-18 11:19 UTC, jensschuppe requested changes

2023-10-18 11:19 UTC, jensschuppe commented on CRM/Fastactivity/Legacycode/Date.php
Let's name this class `CRM_Fastactivity_Legacycode_Form_Date` to resemble the original class name.

2023-10-18 12:18 UTC, jensschuppe commented
Just for reference, https://github.com/systopia/de.systopia.donrec/pull/181 tries to actually replace calls to the `buildDateRange()` method. This should eventually be done here, as well.

2023-10-18 15:09 UTC, jofranz commented
> Just for reference, [systopia/de.systopia.donrec#181](https://github.com/systopia/de.systopia.donrec/pull/181) tries to actually replace calls to the `buildDateRange()` method. This should eventually be done here, as well.

I moved it into #47

2023-10-18 15:10 UTC, jofranz commented on CRM/Fastactivity/Legacycode/Date.php
Would you suggest also placing it into a folder?:
`/Legacycode/Form/Date.php`

2023-10-19 08:37 UTC, jensschuppe commented on CRM/Fastactivity/Legacycode/Date.php
It actually has to, as otherwise the class loader would be unable to find the class.

2023-10-19 10:47 UTC, merged